version: "2"
services:
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
