version: 2
jobs:
    build:
        working_directory: ~/CoursePlanner
        docker:
            - image: node:6.10.1
        steps:
            - checkout
            - setup_remote_docker
            - run: 
                name: Install Docker
                command: |
                    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
                    sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
                    sudo apt-get update
                    sudo apt-get install docker-engine
            - run:
                name: Install Docker Compose
                command: |
                    sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)"
                    sudo chmod +x /usr/local/bin/docker-compose
            - run: docker-compose up

#machine:
#    pre:
#        - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0 #hopefully sets docker to 1.10 instead
#
#    services:
#        - docker
#    node:
#        version:
#            6.10.1
#
#
#dependencies:
#    pre:
#        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#        - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#        - sudo apt-get update
#        - sudo apt-get install google-chrome-stable default-jre libpango1.0-0 firefox
#
#test:
#    pre: 
#        - npm install
#        - npm install -g protractor
#        - docker-compose up:
#            background: true
#        - webdriver-manager update
#        - webdriver-manager start:
#            background: true
#        - sleep 5
#    override:
#        - npm run karma:
#            environment:
#                JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/unit-reports/
#                JUNIT_REPORT_NAME: karma-test-results.xml
#        - protractor protractor.conf.js:
#            environment:
#                E2E_REPORT_PATH: $CIRCLE_TEST_REPORTS/e2e-reports/
